name: Prettier
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.5
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
      - run: npm install
      - run: npm run prettier:check
